server:
  port: 8081
spring:
  application:
    name: manage
  datasource:
    username: admin
    password: admin@rdev
    url: jdbc:mysql://localhost:3306/rdev_sys?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-active: 100
        max-wait: 30000
        max-idle: 20
        min-idle: 0


mybatis:
  type-aliases-package: com.protectdev.manage.mapper
  mapper-locations: classpath:/mapper/*.xml

